title: Ikowave
email: 135090557+ikowave@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
 Ikowave is a podcast that dives deep into the world of artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Ikowave
github_username:  Ikowave
theme: minima
plugins:
  - jekyll-feed

